interface=gw-lab
listen-address=__GATEWAY_IP__
bind-interfaces
dhcp-range=__LAB_DHCP_RANGE_START__,__LAB_DHCP_RANGE_END__,255.255.255.0,12h
domain-needed
bogus-priv
server=__UPSTREAM_DNS1__
server=__UPSTREAM_DNS2__
cache-size=1000
dhcp-authoritative
log-facility=/var/log/dnsmasq-mitm-lab.log
